name: Triggers example
run-name: Mi first trigger
on:
  push: 
    branches: 
      - aprendiendo-github-actions
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
  issues:
    types:
      - labeled
jobs:
   hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr script
        run: node hola-mundo.js
